ExternalProject_Add(usrsctp
	GIT_REPOSITORY https://github.com/sctplab/usrsctp
#	GIT_TAG a05154264872ec8e5d4143ac841a306f54ace231
	GIT_TAG origin/master
	GIT_PROGRESS ON
	INSTALL_DIR ${LOCAL_BUILD_ARTIFACTS_DIR}
	CMAKE_ARGS -DCMAKE_PREFIX_PATH=<INSTALL_DIR>
				-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
				-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
				-DCMAKE_POSITION_INDEPENDENT_CODE=ON
				-Dsctp_werror=OFF
				-Dsctp_build_programs=OFF
)

