ExternalProject_Add(spdlog
	GIT_REPOSITORY https://github.com/gabime/spdlog
	GIT_TAG origin/v1.x
	GIT_PROGRESS ON
	INSTALL_DIR ${LOCAL_BUILD_ARTIFACTS_DIR}
	CMAKE_ARGS -DCMAKE_PREFIX_PATH=<INSTALL_DIR>
				-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
				-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
				-DCMAKE_POSITION_INDEPENDENT_CODE=ON
)
